package org.hyperic.tools.db;
import java.util.Map;


public class EamTableStructure {

	private static java.util.Map m = null ;
	/**
	 * @param args
	 */
	public static void main(String[] args) {
		// TODO Auto-generated method stub
     //Map m = initTableStructure();
     //System.out.println(m.get("eam_agent".toUpperCase()));
     //System.out.println(m.get("EAM_SERVICE_TYPE"));
     //System.out.println(m.get("EAM_PLATFORM"));
     //System.out.println(getTableStructure("eam_server"));
     System.out.println(isColumnInteger("EAM_ALERT_DEFINITION","FREQUENCY_TYPE"));
	}

	public static boolean isColumnInteger(String tableName,String colName){
		if(tableName!=null){
			tableName = tableName.trim();
		}
		if(colName!=null){
			colName = colName.trim();
		}
		System.out.println("table name is "+tableName);
		System.out.println("table colName is "+colName);
		Map map = getTableStructure(tableName);
		System.out.println("map is "+map);
		Object obj = map.get(colName.toUpperCase());
		System.out.println("obj is "+obj);
		String colType = (String)obj;
		System.out.println("tableName: "+tableName+", colName: "+colName+", colType: "+colType);
		if(colType!=null&&(colType.equals("int8")||colType.equals("int4"))){
			return true ;
		}
		return false ;
	}
	public static Map getTableStructure(String tableName){
		if(m==null){
			m = initTableStructure();
		}
		return (Map)m.get(tableName.toUpperCase());
	}
	public static Map initTableStructure(){
		java.util.HashMap hm = new java.util.HashMap();
		java.util.HashMap tableMap = null;
		tableMap = new java.util.HashMap();
		tableMap.put("PLUGIN","varchar(250)");
		tableMap.put("FINTERNAL","bool");
		tableMap.put("SORT_NAME","varchar(500)");
		tableMap.put("NAME","varchar(500)");
		tableMap.put("MTIME","int8");
		tableMap.put("DESCRIPTION","varchar(200)");
		tableMap.put("SERVER_TYPE_ID","int4");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("CTIME","int8");
		tableMap.put("CID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_SERVICE_TYPE",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("id","int4");
		tableMap.put("SET_BY_UI","bool");
		tableMap.put("VC_UUID","varchar(100)");
		tableMap.put("USER_NAME","varchar(50)");
		tableMap.put("primary","key");
		tableMap.put("PASSWORD","varchar(50)");
		tableMap.put("URL","varchar(100)");
		hm.put("EAM_VC_CONFIG",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("FVIRTUAL","bool");
		tableMap.put("PLUGIN","varchar(250)");
		tableMap.put("SORT_NAME","varchar(200)");
		tableMap.put("NAME","varchar(200)");
		tableMap.put("MTIME","int8");
		tableMap.put("DESCRIPTION","varchar(200)");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("CTIME","int8");
		tableMap.put("CID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_SERVER_TYPE",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("ADDITIONAL","int4");
		tableMap.put("primary","key");
		tableMap.put("MEASUREMENT_ID","int4");
		tableMap.put("TIMESTAMP","int8");
		tableMap.put("TYPE","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_METRIC_PROB",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("VALUE","numeric(24");
		tableMap.put("MEASUREMENT_ID","int4");
		tableMap.put("TIMESTAMP","int8");
		hm.put("HQ_METRIC_DATA_4D_1S",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("SUBJECT","varchar(32)");
		tableMap.put("ENTITY_ID","int4");
		tableMap.put("ENTITY_TYPE","int4");
		tableMap.put("JOB_ORDER_DATA","varchar(500)");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("JOBNAME","varchar(128)");
		tableMap.put("NEXTFIRETIME","int8");
		tableMap.put("SCHEDULEVALUEBYTES","bytea");
		tableMap.put("ACTION","varchar(32)");
		tableMap.put("TRIGGERNAME","varchar(128)");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_CONTROL_SCHEDULE",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("VALUE","numeric(24");
		tableMap.put("MEASUREMENT_ID","int4");
		tableMap.put("TIMESTAMP","int8");
		hm.put("HQ_METRIC_DATA_0D_1S",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("GROUP_ID","int4");
		tableMap.put("NAME","varchar(255)");
		tableMap.put("MTIME","int8");
		tableMap.put("SEVERITY","int4");
		tableMap.put("CTIME","int8");
		tableMap.put("VERSION_COL","int8");
		tableMap.put("ENABLED","bool");
		tableMap.put("primary","key");
		tableMap.put("ESCALATION_ID","int4");
		tableMap.put("ID","int4");
		tableMap.put("LAST_FIRED","int8");
		tableMap.put("DELETED","bool");
		tableMap.put("DESCR","varchar(255)");
		hm.put("EAM_GALERT_DEFS",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("REL_ID","int4");
		tableMap.put("DISTANCE","int4");
		tableMap.put("unique","(FROM_ID");
		tableMap.put("FROM_ID","int4");
		tableMap.put("TO_ID","int4");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_RESOURCE_EDGE",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("unique","(ROLE_ID)");
		tableMap.put("USER_ID","int4");
		tableMap.put("CONFIG_TYPE","varchar(255)");
		tableMap.put("primary","key");
		tableMap.put("name","varchar(255)");
		tableMap.put("ID","int4");
		tableMap.put("CRISPO_ID","int4");
		tableMap.put("ROLE_ID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_DASH_CONFIG",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("MAX_EXPECTED_VAL","float8");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("MEASUREMENT_ID","int4");
		tableMap.put("MEAN","float8");
		tableMap.put("USER_ENTERED","bool");
		tableMap.put("MIN_EXPECTED_VAL","float8");
		tableMap.put("COMPUTE_TIME","int8");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_MEASUREMENT_BL",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("TRIGGER_GROUP","varchar(200)");
		hm.put("QRTZ_PAUSED_TRIGGER_GRPS",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("DNS_SERVER","varchar(64)");
		tableMap.put("MTIME","int8");
		tableMap.put("CONTROL_CONFIG","bytea");
		tableMap.put("CUSTOM_PROPERTIES","bytea");
		tableMap.put("QUEUESTATUS","int4");
		tableMap.put("CTIME","int8");
		tableMap.put("AUTO_APPROVE","bool");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("FQDN","varchar(200)");
		tableMap.put("PRODUCT_CONFIG","bytea");
		tableMap.put("NAME","varchar(255)");
		tableMap.put("RAM","int4");
		tableMap.put("DESCRIPTION","varchar(300)");
		tableMap.put("LASTAPPROVED","int8");
		tableMap.put("OS","varchar(80)");
		tableMap.put("DIFF","int8");
		tableMap.put("AGENTTOKEN","varchar(100)");
		tableMap.put("DHCP_SERVER","varchar(64)");
		tableMap.put("GATEWAY","varchar(64)");
		tableMap.put("VERSION_COL","int8");
		tableMap.put("LOCATION","varchar(100)");
		tableMap.put("ARCH","varchar(80)");
		tableMap.put("OSVERSION","varchar(80)");
		tableMap.put("IGNORED","bool");
		tableMap.put("MEASUREMENT_CONFIG","bytea");
		tableMap.put("CERTDN","varchar(200)");
		tableMap.put("CPU_SPEED","int4");
		tableMap.put("CPU_COUNT","int4");
		hm.put("EAM_AIQ_PLATFORM",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("DEPENDENT_SERVICE_ID","int4");
		tableMap.put("unique","(APPSERVICE_ID");
		tableMap.put("MTIME","int8");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("APPSERVICE_ID","int4");
		tableMap.put("CTIME","int8");
		hm.put("EAM_SERVICE_DEP_MAP",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("PROCESS_ID","int4");
		tableMap.put("primary","key");
		tableMap.put("PHYSICAL_ID","int4");
		tableMap.put("RESOURCE_ID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_VIRTUAL",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("SUBJECT","varchar(32)");
		tableMap.put("CONFIG","bytea");
		tableMap.put("GROUP_ID","int4");
		tableMap.put("DESCRIPTION","varchar(500)");
		tableMap.put("STARTTIME","int8");
		tableMap.put("STATUS","varchar(64)");
		tableMap.put("SCHEDULED","bool");
		tableMap.put("VERSION_COL","int8");
		tableMap.put("DATE_SCHEDULED","int8");
		tableMap.put("ENTITY_ID","int4");
		tableMap.put("MESSAGE","varchar(500)");
		tableMap.put("ENTITY_TYPE","int4");
		tableMap.put("BATCH_ID","int4");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("ENDTIME","int8");
		tableMap.put("SCANDESC","varchar(200)");
		tableMap.put("DURATION","int8");
		tableMap.put("SCANNAME","varchar(100)");
		hm.put("EAM_AUTOINV_HISTORY",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("NATURE","int4");
		tableMap.put("ORIGINAL","bool");
		tableMap.put("SUBJECT_ID","int4");
		tableMap.put("START_TIME","int8");
		tableMap.put("OLD_VAL","varchar(1000)");
		tableMap.put("RESOURCE_ID","int4");
		tableMap.put("IMPORTANCE","int4");
		tableMap.put("VERSION_COL","int8");
		tableMap.put("PURPOSE","int4");
		tableMap.put("MESSAGE","varchar(1000)");
		tableMap.put("KLAZZ","varchar(255)");
		tableMap.put("FIELD","varchar(100)");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("NEW_VAL","varchar(1000)");
		tableMap.put("END_TIME","int8");
		tableMap.put("PARENT_ID","int4");
		hm.put("EAM_AUDIT",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("MAX_WAIT_TIME","int8");
		tableMap.put("ALLOW_PAUSE","bool");
		tableMap.put("NOTIFY_ALL","bool");
		tableMap.put("NAME","varchar(200)");
		tableMap.put("MTIME","int8");
		tableMap.put("DESCRIPTION","varchar(250)");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("FREPEAT","bool");
		tableMap.put("CTIME","int8");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_ESCALATION",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("RESOURCE_GROUP_ID","int4");
		tableMap.put("unique","(RESOURCE_ID");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("RESOURCE_ID","int4");
		tableMap.put("CTIME","int8");
		hm.put("EAM_POLICY_GRP_MAP",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("VALUE","numeric(24");
		tableMap.put("MEASUREMENT_ID","int4");
		tableMap.put("TIMESTAMP","int8");
		hm.put("HQ_METRIC_DATA_4D_0S",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("SUBJECT","varchar(32)");
		tableMap.put("GROUP_ID","int4");
		tableMap.put("DESCRIPTION","varchar(500)");
		tableMap.put("STARTTIME","int8");
		tableMap.put("STATUS","varchar(64)");
		tableMap.put("SCHEDULED","bool");
		tableMap.put("VERSION_COL","int8");
		tableMap.put("DATE_SCHEDULED","int8");
		tableMap.put("ENTITY_ID","int4");
		tableMap.put("ARGS","varchar(500)");
		tableMap.put("MESSAGE","varchar(500)");
		tableMap.put("ENTITY_TYPE","int4");
		tableMap.put("BATCH_ID","int4");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("ENDTIME","int8");
		tableMap.put("ACTION","varchar(32)");
		hm.put("EAM_CONTROL_HISTORY",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("MINVALUE","numeric(24");
		tableMap.put("primary","key");
		tableMap.put("VALUE","numeric(24");
		tableMap.put("MAXVALUE","numeric(24");
		tableMap.put("MEASUREMENT_ID","int4");
		tableMap.put("TIMESTAMP","int8");
		hm.put("EAM_MEASUREMENT_DATA_1D",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("VALUE","numeric(24");
		tableMap.put("MEASUREMENT_ID","int4");
		tableMap.put("TIMESTAMP","int8");
		hm.put("HQ_METRIC_DATA_0D_0S",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("ENABLED","bool");
		tableMap.put("unique","(INSTANCE_ID");
		tableMap.put("DSN","varchar(2048)");
		tableMap.put("MTIME","int8");
		tableMap.put("INSTANCE_ID","int4");
		tableMap.put("primary","key");
		tableMap.put("COLL_INTERVAL","int8");
		tableMap.put("ID","int4");
		tableMap.put("TEMPLATE_ID","int4");
		tableMap.put("RESOURCE_ID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_MEASUREMENT",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("UPMODE","int4");
		tableMap.put("IGNORED","bool");
		tableMap.put("REPORT","varchar(4000)");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_UPDATE_STATUS",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("NETMASK","varchar(64)");
		tableMap.put("unique","(PLATFORM_ID");
		tableMap.put("MTIME","int8");
		tableMap.put("primary","key");
		tableMap.put("ADDRESS","varchar(64)");
		tableMap.put("MAC_ADDRESS","varchar(64)");
		tableMap.put("ID","int4");
		tableMap.put("PLATFORM_ID","int4");
		tableMap.put("CTIME","int8");
		tableMap.put("CID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_IP",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("MINVALUE","numeric(24");
		tableMap.put("primary","key");
		tableMap.put("VALUE","numeric(24");
		tableMap.put("MAXVALUE","numeric(24");
		tableMap.put("MEASUREMENT_ID","int4");
		tableMap.put("TIMESTAMP","int8");
		hm.put("EAM_MEASUREMENT_DATA_1H",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("REPEAT_INTERVAL","int8");
		tableMap.put("REPEAT_COUNT","int8");
		tableMap.put("primary","key");
		tableMap.put("TRIGGER_NAME","varchar(200)");
		tableMap.put("TIMES_TRIGGERED","int8");
		tableMap.put("TRIGGER_GROUP","varchar(200)");
		hm.put("QRTZ_SIMPLE_TRIGGERS",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("unique","(NAME");
		tableMap.put("NAME","varchar(100)");
		tableMap.put("RESOURCE_TYPE_ID","int4");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_OPERATION",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("VCUUID","varchar(128)");
		tableMap.put("primary","key");
		tableMap.put("MACS_ADDRESS","varchar(512)");
		tableMap.put("MOID","varchar(64)");
		tableMap.put("VM_NAME","varchar(128)");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_VM_MAPPING",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("CREATED_BY","varchar(128)");
		tableMap.put("NAME","varchar(128)");
		tableMap.put("DESCRIPTION","varchar(128)");
		tableMap.put("primary","key");
		tableMap.put("RESOURCE_NAME_REGEX","varchar(128)");
		tableMap.put("ID","int4");
		tableMap.put("CTIME","int8");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_GROUP_CRITERIA",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("FREQUENCY","int8");
		tableMap.put("CONFIG","bytea");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("ALERT_DEFINITION_ID","int4");
		tableMap.put("CLASSNAME","varchar(200)");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_REGISTERED_TRIGGER",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("CATEGORY","varchar(255)");
		tableMap.put("ATTACH_ID","int4");
		tableMap.put("primary","key");
		hm.put("EAM_UI_ATTACH_MAST",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("LAST_CHECKIN_TIME","int8");
		tableMap.put("CHECKIN_INTERVAL","int8");
		tableMap.put("INSTANCE_NAME","varchar(200)");
		hm.put("QRTZ_SCHEDULER_STATE",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("SUBJECT_ID","int4");
		tableMap.put("ROLE_ID","int4");
		hm.put("EAM_SUBJECT_ROLE_MAP",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("VALUE","numeric(24");
		tableMap.put("MEASUREMENT_ID","int4");
		tableMap.put("TIMESTAMP","int8");
		hm.put("HQ_METRIC_DATA_8D_0S",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("NETMASK","varchar(64)");
		tableMap.put("unique","(AIQ_PLATFORM_ID");
		tableMap.put("MTIME","int8");
		tableMap.put("IGNORED","bool");
		tableMap.put("primary","key");
		tableMap.put("ADDRESS","varchar(64)");
		tableMap.put("MAC_ADDRESS","varchar(64)");
		tableMap.put("ID","int4");
		tableMap.put("DIFF","int8");
		tableMap.put("QUEUESTATUS","int4");
		tableMap.put("AIQ_PLATFORM_ID","int4");
		tableMap.put("CTIME","int8");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_AIQ_IP",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("OPERATION_ID","int4");
		tableMap.put("ROLE_ID","int4");
		hm.put("EAM_ROLE_OPERATION_MAP",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("CATEGORY","varchar(255)");
		tableMap.put("ATTACH_ID","int4");
		tableMap.put("primary","key");
		tableMap.put("RESOURCE_ID","int4");
		hm.put("EAM_UI_ATTACH_RSRC",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("VALUE","numeric(24");
		tableMap.put("MEASUREMENT_ID","int4");
		tableMap.put("TIMESTAMP","int8");
		hm.put("HQ_METRIC_DATA_5D_0S",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("SERVER_TYPE_ID","int4");
		tableMap.put("primary","key");
		tableMap.put("PLATFORM_TYPE_ID","int4");
		hm.put("EAM_PLATFORM_SERVER_TYPE_MAP",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("VIEW_ID","int4");
		hm.put("EAM_UI_VIEW_RESOURCE",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("ALERT_TYPE","int4");
		tableMap.put("primary","key");
		tableMap.put("SUBJECT_ID","int4");
		tableMap.put("DETAIL","varchar(500)");
		tableMap.put("ID","int4");
		tableMap.put("TIMESTAMP","int8");
		tableMap.put("ACTION_ID","int4");
		tableMap.put("ALERT_ID","int4");
		hm.put("EAM_ALERT_ACTION_LOG",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("unique","(NAME)");
		tableMap.put("NAME","varchar(255)");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_CALENDAR",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("MGMT_POLICY_ID","int4");
		tableMap.put("primary","key");
		tableMap.put("COLL_INTERVAL","int8");
		tableMap.put("ID","int4");
		tableMap.put("TEMPLATE_ID","int4");
		tableMap.put("DEFAULT_ON","bool");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_MEAS_INSTR",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("RESOURCE_GROUP_ID","int4");
		tableMap.put("unique","(RESOURCE_ID");
		tableMap.put("ENTRY_TIME","int8");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("RESOURCE_ID","int4");
		hm.put("EAM_RES_GRP_RES_MAP",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("SERVICEID","int4");
		tableMap.put("ID","int4");
		tableMap.put("URL","varchar(767)");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_SERVICE_REQUEST",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("JOB_CLASS_NAME","varchar(250)");
		tableMap.put("JOB_GROUP","varchar(200)");
		tableMap.put("JOB_NAME","varchar(200)");
		tableMap.put("JOB_DATA","bytea");
		tableMap.put("IS_STATEFUL","bool");
		tableMap.put("DESCRIPTION","varchar(250)");
		tableMap.put("IS_VOLATILE","bool");
		tableMap.put("IS_DURABLE","bool");
		tableMap.put("primary","key");
		tableMap.put("REQUESTS_RECOVERY","bool");
		hm.put("QRTZ_JOB_DETAILS",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("unique","(POLICY_ID");
		tableMap.put("CONFIG_STATUS_BUF","varchar(512)");
		tableMap.put("MTIME","int8");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("RESOURCE_ID","int4");
		tableMap.put("POLICY_ID","int4");
		tableMap.put("CONFIG_STATUS","int4");
		tableMap.put("CTIME","int8");
		hm.put("EAM_POLICY_RESOURCE_STATUS",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("STARTIME","int8");
		tableMap.put("primary","key");
		tableMap.put("AVAILVAL","float8");
		tableMap.put("ENDTIME","int8");
		tableMap.put("MEASUREMENT_ID","int4");
		hm.put("HQ_AVAIL_DATA_RLE",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("LOCK_NAME","varchar(40)");
		hm.put("QRTZ_LOCKS",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("CATEGORY","varchar(255)");
		tableMap.put("ATTACH_ID","int4");
		tableMap.put("primary","key");
		hm.put("EAM_UI_ATTACH_ADMIN",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("GROUP_ID","int4");
		tableMap.put("unique","(SERVICE_ID");
		tableMap.put("MTIME","int8");
		tableMap.put("primary","key");
		tableMap.put("ISGROUP","bool");
		tableMap.put("APPLICATION_ID","int4");
		tableMap.put("ID","int4");
		tableMap.put("SERVICE_TYPE_ID","int4");
		tableMap.put("MODIFIED_BY","varchar(100)");
		tableMap.put("SERVICE_ID","int4");
		tableMap.put("CTIME","int8");
		tableMap.put("FENTRY_POINT","bool");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_APP_SERVICE",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("THRESHOLD","float8");
		tableMap.put("NAME","varchar(100)");
		tableMap.put("COMPARATOR","varchar(2)");
		tableMap.put("primary","key");
		tableMap.put("REQUIRED","bool");
		tableMap.put("ID","int4");
		tableMap.put("ALERT_DEFINITION_ID","int4");
		tableMap.put("MEASUREMENT_ID","int4");
		tableMap.put("TRIGGER_ID","int4");
		tableMap.put("OPTION_STATUS","varchar(150)");
		tableMap.put("TYPE","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_ALERT_CONDITION",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("ALERT_DEFINITION_ID","int4");
		tableMap.put("FIXED","bool");
		tableMap.put("CTIME","int8");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_ALERT",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("unique","(NAME");
		tableMap.put("NAME","varchar(100)");
		tableMap.put("SORT_NAME","varchar(100)");
		tableMap.put("DSN","varchar(100)");
		tableMap.put("FSYSTEM","bool");
		tableMap.put("HTML_EMAIL","bool");
		tableMap.put("FACTIVE","bool");
		tableMap.put("PREF_CRISPO_ID","int4");
		tableMap.put("RESOURCE_ID","int4");
		tableMap.put("LAST_NAME","varchar(100)");
		tableMap.put("PHONE_NUMBER","varchar(100)");
		tableMap.put("VERSION_COL","int8");
		tableMap.put("FIRST_NAME","varchar(100)");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("DEPARTMENT","varchar(100)");
		tableMap.put("EMAIL_ADDRESS","varchar(100)");
		tableMap.put("SMS_ADDRESS","varchar(100)");
		hm.put("EAM_SUBJECT",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("VALUE","numeric(24");
		tableMap.put("MEASUREMENT_ID","int4");
		tableMap.put("TIMESTAMP","int8");
		hm.put("HQ_METRIC_DATA_8D_1S",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("AUX_LOG_ID","int4");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("METRIC_ID","int4");
		tableMap.put("DEF_ID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_METRIC_AUX_LOGS",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("VIEW_ID","int4");
		hm.put("EAM_UI_VIEW_MASTHEAD",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("unique","(ID");
		tableMap.put("DESCRIPTION","varchar(200)");
		tableMap.put("MTIME","int8");
		tableMap.put("AUTODISCOVERY_ZOMBIE","bool");
		tableMap.put("SERVICE_RT","bool");
		tableMap.put("RESOURCE_ID","int4");
		tableMap.put("AUTOINVENTORYIDENTIFIER","varchar(500)");
		tableMap.put("CTIME","int8");
		tableMap.put("VERSION_COL","int8");
		tableMap.put("CID","int4");
		tableMap.put("LOCATION","varchar(100)");
		tableMap.put("PARENT_SERVICE_ID","int4");
		tableMap.put("CONFIG_RESPONSE_ID","int4");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("SERVER_ID","int4");
		tableMap.put("ENDUSER_RT","bool");
		tableMap.put("SERVICE_TYPE_ID","int4");
		tableMap.put("MODIFIED_BY","varchar(100)");
		hm.put("EAM_SERVICE",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("SUBJECT","varchar(100)");
		tableMap.put("INSTANCE_ID","int4");
		tableMap.put("primary","key");
		tableMap.put("DETAIL","varchar(4000)");
		tableMap.put("ID","int4");
		tableMap.put("STATUS","varchar(100)");
		tableMap.put("RESOURCE_ID","int4");
		tableMap.put("TIMESTAMP","int8");
		tableMap.put("TYPE","varchar(100)");
		hm.put("EAM_EVENT_LOG",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("SORT_NAME","varchar(200)");
		tableMap.put("NAME","varchar(200)");
		tableMap.put("MTIME","int8");
		tableMap.put("DESCRIPTION","varchar(200)");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("CTIME","int8");
		tableMap.put("CID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_APPLICATION_TYPE",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("CALENDAR_ID","int4");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_CALENDAR_ENT",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("VALUE","numeric(24");
		tableMap.put("MEASUREMENT_ID","int4");
		tableMap.put("TIMESTAMP","int8");
		hm.put("HQ_METRIC_DATA_5D_1S",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("IDX","int4");
		tableMap.put("VAL","varchar(4000)");
		tableMap.put("primary","key");
		tableMap.put("OPT_ID","int4");
		hm.put("EAM_CRISPO_ARRAY",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("PASSWORD","varchar(64)");
		tableMap.put("PRINCIPAL","varchar(64)");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_PRINCIPAL",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("GROUP_CRITERIA_ID","int4");
		tableMap.put("CLUSTER_ID","int4");
		tableMap.put("DESCRIPTION","varchar(100)");
		tableMap.put("FSYSTEM","bool");
		tableMap.put("GROUPTYPE","int4");
		tableMap.put("MTIME","int8");
		tableMap.put("RESOURCE_ID","int4");
		tableMap.put("CTIME","int8");
		tableMap.put("VERSION_COL","int8");
		tableMap.put("LOCATION","varchar(100)");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("MODIFIED_BY","varchar(100)");
		tableMap.put("RESOURCE_PROTOTYPE","int4");
		hm.put("EAM_RESOURCE_GROUP",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("SORT_NAME","varchar(100)");
		tableMap.put("NAME","varchar(100)");
		tableMap.put("FSYSTEM","bool");
		tableMap.put("DESCRIPTION","varchar(100)");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("RESOURCE_ID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_ROLE",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("unique","(ROLE_ID");
		tableMap.put("CALENDAR_ID","int4");
		tableMap.put("primary","key");
		tableMap.put("CALTYPE","int4");
		tableMap.put("ID","int4");
		tableMap.put("ROLE_ID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_ROLE_CALENDAR",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("VALUE","numeric(24");
		tableMap.put("MEASUREMENT_ID","int4");
		tableMap.put("TIMESTAMP","int8");
		hm.put("HQ_METRIC_DATA_7D_0S",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("I","int8");
		hm.put("EAM_NUMBERS",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("time","timestamp");
		tableMap.put("resourceId","int4");
		tableMap.put("primary","key");
		tableMap.put("data","bytea");
		hm.put("TopNData",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("ALERT_TYPE","int4");
		tableMap.put("primary","key");
		tableMap.put("SUBJECT_ID","int4");
		tableMap.put("DETAIL","varchar(1024)");
		tableMap.put("ID","int4");
		tableMap.put("GALERT_ID","int4");
		tableMap.put("TIMESTAMP","int8");
		tableMap.put("ACTION_ID","int4");
		hm.put("EAM_GALERT_ACTION_LOG",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("VAL","varchar(4000)");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("CRISPO_ID","int4");
		tableMap.put("PROPKEY","varchar(255)");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_CRISPO_OPT",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("SRN","int4");
		tableMap.put("INSTANCE_ID","int4");
		tableMap.put("primary","key");
		tableMap.put("APPDEF_TYPE","int4");
		tableMap.put("LAST_SCHEDULE_TIME","int8");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_SRN",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("CRON_EXPRESSION","varchar(200)");
		tableMap.put("primary","key");
		tableMap.put("TRIGGER_NAME","varchar(200)");
		tableMap.put("TIME_ZONE_ID","varchar(80)");
		tableMap.put("TRIGGER_GROUP","varchar(200)");
		hm.put("QRTZ_CRON_TRIGGERS",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("NAME","varchar(100)");
		tableMap.put("PLUGIN_VERSION","varchar(30)");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_UI_PLUGIN",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("NAME","varchar(100)");
		tableMap.put("FSYSTEM","bool");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("RESOURCE_ID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_RESOURCE_TYPE",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("NAME","varchar(80)");
		tableMap.put("MTIME","int8");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("CTIME","int8");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_AGENT_TYPE",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("VALUE","numeric(24");
		tableMap.put("MEASUREMENT_ID","int4");
		tableMap.put("TIMESTAMP","int8");
		hm.put("HQ_METRIC_DATA_7D_1S",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("IDX","int4");
		tableMap.put("primary","key");
		tableMap.put("ESCALATION_ID","int4");
		tableMap.put("ACTION_ID","int4");
		tableMap.put("WAIT_TIME","int8");
		hm.put("EAM_ESCALATION_ACTION",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("unique","(APPDEF_ID");
		tableMap.put("APPDEF_ID","int4");
		tableMap.put("PROPVALUE","varchar(1000)");
		tableMap.put("VALUE_IDX","int4");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("KEYID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_CPROP",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("NAME","varchar(100)");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_MEASUREMENT_CAT",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("DESCRIPTION","varchar(1024)");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("CRISPO_ID","int4");
		tableMap.put("RESOURCE_ID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_MGMT_POLICY",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("TRIGGER_LISTENER","varchar(200)");
		tableMap.put("primary","key");
		tableMap.put("TRIGGER_NAME","varchar(200)");
		tableMap.put("TRIGGER_GROUP","varchar(200)");
		hm.put("QRTZ_TRIGGER_LISTENERS",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("APPDEF_TYPEID","int4");
		tableMap.put("unique","(APPDEF_TYPE");
		tableMap.put("DESCRIPTION","varchar(200)");
		tableMap.put("primary","key");
		tableMap.put("APPDEF_TYPE","int4");
		tableMap.put("ID","int4");
		tableMap.put("PROPKEY","varchar(100)");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_CPROP_KEY",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("APPDEF_ID","int4");
		tableMap.put("AUX_LOG_ID","int4");
		tableMap.put("primary","key");
		tableMap.put("APPDEF_TYPE","int4");
		tableMap.put("ID","int4");
		tableMap.put("DEF_ID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_RESOURCE_AUX_LOGS",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("DESCRIPTION","varchar(64)");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("CODE","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_ERROR_CODE",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("CONFIG_ID","int4");
		tableMap.put("TYPE_ID","int4");
		tableMap.put("ID","int4");
		tableMap.put("PARTITION","int4");
		tableMap.put("DEF_ID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_EXEC_STRATEGIES",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("AUTHTOKEN","varchar(100)");
		tableMap.put("MTIME","int8");
		tableMap.put("UNIDIRECTIONAL","bool");
		tableMap.put("AGENT_TYPE_ID","int4");
		tableMap.put("ADDRESS","varchar(255)");
		tableMap.put("AGENTTOKEN","varchar(100)");
		tableMap.put("LAST_PLUGIN_INVENTORY_CHECKIN","int8");
		tableMap.put("CTIME","int8");
		tableMap.put("VERSION_COL","int8");
		tableMap.put("PORT","int4");
		tableMap.put("VERSION","varchar(50)");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("PLUGIN_INVENTORY_CHECKSUM","varchar(128)");
		hm.put("EAM_AGENT",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("LAST_SYNC_STATUS","varchar(64)");
		tableMap.put("PLUGIN_NAME","varchar(200)");
		tableMap.put("FILE_NAME","varchar(128)");
		tableMap.put("LAST_SYNC_ATTEMPT","int8");
		tableMap.put("PRODUCT_NAME","varchar(128)");
		tableMap.put("primary","key");
		tableMap.put("LAST_CHECKIN","int8");
		tableMap.put("MD5","varchar(100)");
		tableMap.put("ID","int4");
		tableMap.put("AGENT_ID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_AGENT_PLUGIN_STATUS",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_CRISPO",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("LAST_FIRED","int8");
		tableMap.put("ALERT_DEFINITION_ID","int4");
		hm.put("EAM_ALERT_DEF_STATE",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("AUXTYPE","int4");
		tableMap.put("PARENT","int4");
		tableMap.put("DESCRIPTION","varchar(255)");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("GALERT_ID","int4");
		tableMap.put("TIMESTAMP","int8");
		tableMap.put("DEF_ID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_GALERT_AUX_LOGS",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("DESCRIPTION","varchar(256)");
		tableMap.put("MTIME","int8");
		tableMap.put("PLATFORM_TYPE_ID","int4");
		tableMap.put("RESOURCE_ID","int4");
		tableMap.put("CTIME","int8");
		tableMap.put("VERSION_COL","int8");
		tableMap.put("CID","int4");
		tableMap.put("LOCATION","varchar(100)");
		tableMap.put("CONFIG_RESPONSE_ID","int4");
		tableMap.put("COMMENT_TEXT","varchar(256)");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("MODIFIED_BY","varchar(100)");
		tableMap.put("AGENT_ID","int4");
		tableMap.put("CERTDN","varchar(200)");
		tableMap.put("FQDN","varchar(255)");
		tableMap.put("CPU_COUNT","int4");
		hm.put("EAM_PLATFORM",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("ATTACH_TIME","int8");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("VIEW_ID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_UI_ATTACHMENT",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("PLUGIN","varchar(250)");
		tableMap.put("ARCH","varchar(80)");
		tableMap.put("OSVERSION","varchar(80)");
		tableMap.put("SORT_NAME","varchar(80)");
		tableMap.put("NAME","varchar(80)");
		tableMap.put("MTIME","int8");
		tableMap.put("DESCRIPTION","varchar(256)");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("OS","varchar(80)");
		tableMap.put("CTIME","int8");
		tableMap.put("CID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_PLATFORM_TYPE",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("VALUE","numeric(24");
		tableMap.put("MEASUREMENT_ID","int4");
		tableMap.put("TIMESTAMP","int8");
		hm.put("HQ_METRIC_DATA_2D_1S",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("VALUE","varchar(250)");
		tableMap.put("ID","int4");
		tableMap.put("CONDITION_ID","int4");
		tableMap.put("ALERT_ID","int4");
		hm.put("EAM_ALERT_CONDITION_LOG",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("TYPE_CLASS","varchar(255)");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_GTRIGGER_TYPES",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("SORT_NAME","varchar(500)");
		tableMap.put("NAME","varchar(500)");
		tableMap.put("MTIME","int8");
		tableMap.put("FSYSTEM","bool");
		tableMap.put("INSTANCE_ID","int4");
		tableMap.put("RESOURCE_TYPE_ID","int4");
		tableMap.put("primary","key");
		tableMap.put("SUBJECT_ID","int4");
		tableMap.put("ID","int4");
		tableMap.put("PROTO_ID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_RESOURCE",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("VALUE","numeric(24");
		tableMap.put("MEASUREMENT_ID","int4");
		tableMap.put("TIMESTAMP","int8");
		hm.put("HQ_METRIC_DATA_6D_1S",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("APPLICATION_TYPE_ID","int4");
		tableMap.put("primary","key");
		tableMap.put("SERVICE_TYPE_ID","int4");
		hm.put("EAM_APP_TYPE_SERVICE_TYPE_MAP",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("CALENDAR","bytea");
		tableMap.put("primary","key");
		tableMap.put("CALENDAR_NAME","varchar(200)");
		hm.put("QRTZ_CALENDARS",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("VIEW_ID","int4");
		hm.put("EAM_UI_VIEW_ADMIN",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("ATTACH_TYPE","int4");
		tableMap.put("DESCRIPTION","varchar(255)");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("PATH","varchar(255)");
		tableMap.put("UI_PLUGIN_ID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_UI_VIEW",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("JOB_GROUP","varchar(200)");
		tableMap.put("JOB_DATA","bytea");
		tableMap.put("DESCRIPTION","varchar(250)");
		tableMap.put("PRIORITY","int4");
		tableMap.put("PREV_FIRE_TIME","int8");
		tableMap.put("TRIGGER_NAME","varchar(200)");
		tableMap.put("START_TIME","int8");
		tableMap.put("JOB_NAME","varchar(200)");
		tableMap.put("MISFIRE_INSTR","int4");
		tableMap.put("IS_VOLATILE","bool");
		tableMap.put("primary","key");
		tableMap.put("TRIGGER_STATE","varchar(16)");
		tableMap.put("TRIGGER_TYPE","varchar(8)");
		tableMap.put("CALENDAR_NAME","varchar(200)");
		tableMap.put("NEXT_FIRE_TIME","int8");
		tableMap.put("END_TIME","int8");
		tableMap.put("TRIGGER_GROUP","varchar(200)");
		hm.put("QRTZ_TRIGGERS",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("DEFAULT_PROPVALUE","varchar(300)");
		tableMap.put("PREFIX","varchar(80)");
		tableMap.put("unique","(PREFIX");
		tableMap.put("FREAD_ONLY","bool");
		tableMap.put("PROPVALUE","varchar(300)");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("PROPKEY","varchar(80)");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_CONFIG_PROPS",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("ENG_CONTACT","varchar(100)");
		tableMap.put("LOCATION","varchar(100)");
		tableMap.put("MTIME","int8");
		tableMap.put("DESCRIPTION","varchar(500)");
		tableMap.put("APPLICATION_TYPE_ID","int4");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("OPS_CONTACT","varchar(100)");
		tableMap.put("MODIFIED_BY","varchar(100)");
		tableMap.put("RESOURCE_ID","int4");
		tableMap.put("CTIME","int8");
		tableMap.put("BUS_CONTACT","varchar(100)");
		tableMap.put("CID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_APPLICATION",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("SUBJECT","varchar(32)");
		tableMap.put("CONFIG","bytea");
		tableMap.put("JOB_ORDER_DATA","varchar(500)");
		tableMap.put("TRIGGERNAME","varchar(128)");
		tableMap.put("VERSION_COL","int8");
		tableMap.put("ENTITY_ID","int4");
		tableMap.put("ENTITY_TYPE","int4");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("NEXTFIRETIME","int8");
		tableMap.put("JOBNAME","varchar(128)");
		tableMap.put("SCHEDULEVALUEBYTES","bytea");
		tableMap.put("SCANDESC","varchar(200)");
		tableMap.put("SCANNAME","varchar(100)");
		hm.put("EAM_AUTOINV_SCHEDULE",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("JOB_GROUP","varchar(200)");
		tableMap.put("JOB_NAME","varchar(200)");
		tableMap.put("JOB_LISTENER","varchar(200)");
		tableMap.put("primary","key");
		hm.put("QRTZ_JOB_LISTENERS",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("PRODUCT_CONFIG","bytea");
		tableMap.put("NAME","varchar(255)");
		tableMap.put("DESCRIPTION","varchar(300)");
		tableMap.put("MTIME","int8");
		tableMap.put("CONTROL_CONFIG","bytea");
		tableMap.put("RESPONSETIME_CONFIG","bytea");
		tableMap.put("CUSTOM_PROPERTIES","bytea");
		tableMap.put("QUEUESTATUS","int4");
		tableMap.put("DIFF","int8");
		tableMap.put("CTIME","int8");
		tableMap.put("VERSION_COL","int8");
		tableMap.put("SERVICETYPENAME","varchar(200)");
		tableMap.put("IGNORED","bool");
		tableMap.put("primary","key");
		tableMap.put("MEASUREMENT_CONFIG","bytea");
		tableMap.put("ID","int4");
		tableMap.put("SERVER_ID","int4");
		hm.put("EAM_AIQ_SERVICE",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("VALUE","numeric(24");
		tableMap.put("MEASUREMENT_ID","int4");
		tableMap.put("TIMESTAMP","int8");
		hm.put("HQ_METRIC_DATA_3D_0S",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("unique","(PLATFORM_ID");
		tableMap.put("DESCRIPTION","varchar(300)");
		tableMap.put("MTIME","int8");
		tableMap.put("AUTODISCOVERY_ZOMBIE","bool");
		tableMap.put("INSTALLPATH","varchar(200)");
		tableMap.put("RESOURCE_ID","int4");
		tableMap.put("CTIME","int8");
		tableMap.put("AUTOINVENTORYIDENTIFIER","varchar(250)");
		tableMap.put("VERSION_COL","int8");
		tableMap.put("CID","int4");
		tableMap.put("LOCATION","varchar(100)");
		tableMap.put("CONFIG_RESPONSE_ID","int4");
		tableMap.put("SERVER_TYPE_ID","int4");
		tableMap.put("primary","key");
		tableMap.put("RUNTIMEAUTODISCOVERY","bool");
		tableMap.put("ID","int4");
		tableMap.put("MODIFIED_BY","varchar(100)");
		tableMap.put("PLATFORM_ID","int4");
		tableMap.put("SERVICESAUTOMANAGED","bool");
		tableMap.put("WASAUTODISCOVERED","bool");
		hm.put("EAM_SERVER",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("startTime","int4");
		tableMap.put("weekDay","int4");
		tableMap.put("primary","key");
		tableMap.put("CALENDAR_WEEK_ID","int4");
		tableMap.put("endTime","int4");
		hm.put("EAM_CALENDAR_WEEK",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("VALUE","numeric(24");
		tableMap.put("MEASUREMENT_ID","int4");
		tableMap.put("TIMESTAMP","int8");
		hm.put("HQ_METRIC_DATA_COMPAT",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("UNITS","varchar(50)");
		tableMap.put("NAME","varchar(100)");
		tableMap.put("MTIME","int8");
		tableMap.put("TEMPLATE","varchar(2048)");
		tableMap.put("COLLECTION_TYPE","int4");
		tableMap.put("CTIME","int8");
		tableMap.put("VERSION_COL","int8");
		tableMap.put("ALIAS","varchar(100)");
		tableMap.put("DEFAULT_INTERVAL","int8");
		tableMap.put("DESIGNATE","bool");
		tableMap.put("PLUGIN","varchar(250)");
		tableMap.put("primary","key");
		tableMap.put("MONITORABLE_TYPE_ID","int4");
		tableMap.put("ID","int4");
		tableMap.put("CATEGORY_ID","int4");
		tableMap.put("DEFAULT_ON","bool");
		hm.put("EAM_MEASUREMENT_TEMPL",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("CONFIG","bytea");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("ALERT_DEFINITION_ID","int4");
		tableMap.put("DELETED","bool");
		tableMap.put("PARENT_ID","int4");
		tableMap.put("CLASSNAME","varchar(200)");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_ACTION",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("VALUE","numeric(24");
		tableMap.put("MEASUREMENT_ID","int4");
		tableMap.put("TIMESTAMP","int8");
		hm.put("HQ_METRIC_DATA_1D_1S",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("MINVALUE","numeric(24");
		tableMap.put("primary","key");
		tableMap.put("VALUE","numeric(24");
		tableMap.put("MAXVALUE","numeric(24");
		tableMap.put("MEASUREMENT_ID","int4");
		tableMap.put("TIMESTAMP","int8");
		hm.put("EAM_MEASUREMENT_DATA_6H",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("RESOURCE_GROUP_ID","int4");
		tableMap.put("primary","key");
		tableMap.put("ROLE_ID","int4");
		hm.put("EAM_ROLE_RESOURCE_GROUP_MAP",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("TRIGGER_NAME","varchar(200)");
		tableMap.put("TRIGGER_GROUP","varchar(200)");
		tableMap.put("BLOB_DATA","bytea");
		hm.put("QRTZ_BLOB_TRIGGERS",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("numberOfProcesses","int4");
		tableMap.put("ENABLED","bool");
		tableMap.put("resourceId","int4");
		tableMap.put("intervalInMinutes","int4");
		tableMap.put("primary","key");
		tableMap.put("lastUpdated","int8");
		hm.put("TopNSchedule",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("CRITERIA_ID","int4");
		tableMap.put("PROTOTYPE_ID","int4");
		hm.put("EAM_GROUP_CRITERIA_PROTOTYPE_MAP",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("VALUE","numeric(24");
		tableMap.put("MEASUREMENT_ID","int4");
		tableMap.put("TIMESTAMP","int8");
		hm.put("HQ_METRIC_DATA_2D_0S",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("TYPE_CLASS","varchar(255)");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_EXEC_STRATEGY_TYPES",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("VALUE","numeric(24");
		tableMap.put("MEASUREMENT_ID","int4");
		tableMap.put("TIMESTAMP","int8");
		hm.put("HQ_METRIC_DATA_6D_0S",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("LONG_REASON","varchar(2048)");
		tableMap.put("primary","key");
		tableMap.put("ID","int4");
		tableMap.put("PARTITION","int4");
		tableMap.put("SHORT_REASON","varchar(256)");
		tableMap.put("TIMESTAMP","int8");
		tableMap.put("FIXED","bool");
		tableMap.put("DEF_ID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_GALERT_LOGS",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("CONFIG_ID","int4");
		tableMap.put("TYPE_ID","int4");
		tableMap.put("ID","int4");
		tableMap.put("STRAT_ID","int4");
		tableMap.put("LIDX","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_GTRIGGERS",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("unique","(ALERT_DEF_ID");
		tableMap.put("NEXT_ACTION_IDX","int4");
		tableMap.put("ALERT_TYPE","int4");
		tableMap.put("primary","key");
		tableMap.put("ESCALATION_ID","int4");
		tableMap.put("ID","int4");
		tableMap.put("NEXT_ACTION_TIME","int8");
		tableMap.put("ALERT_DEF_ID","int4");
		tableMap.put("ACKNOWLEDGED_BY","int4");
		tableMap.put("ALERT_ID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_ESCALATION_STATE",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("unique","(NAME)");
		tableMap.put("NAME","varchar(255)");
		tableMap.put("primary","key");
		tableMap.put("IS_HIER","bool");
		tableMap.put("ID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_RESOURCE_RELATION",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("PLUGIN","varchar(250)");
		tableMap.put("NAME","varchar(100)");
		tableMap.put("primary","key");
		tableMap.put("APPDEF_TYPE","int4");
		tableMap.put("ID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_MONITORABLE_TYPE",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("VALUE","numeric(24");
		tableMap.put("MEASUREMENT_ID","int4");
		tableMap.put("TIMESTAMP","int8");
		hm.put("HQ_METRIC_DATA_3D_1S",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("PRODUCT_CONFIG","bytea");
		tableMap.put("unique","(AIQ_PLATFORM_ID");
		tableMap.put("NAME","varchar(255)");
		tableMap.put("MTIME","int8");
		tableMap.put("DESCRIPTION","varchar(300)");
		tableMap.put("CONTROL_CONFIG","bytea");
		tableMap.put("RESPONSETIME_CONFIG","bytea");
		tableMap.put("INSTALLPATH","varchar(255)");
		tableMap.put("CUSTOM_PROPERTIES","bytea");
		tableMap.put("DIFF","int8");
		tableMap.put("QUEUESTATUS","int4");
		tableMap.put("CTIME","int8");
		tableMap.put("AUTOINVENTORYIDENTIFIER","varchar(255)");
		tableMap.put("VERSION_COL","int8");
		tableMap.put("AUTO_APPROVE","bool");
		tableMap.put("IGNORED","bool");
		tableMap.put("primary","key");
		tableMap.put("SERVERTYPENAME","varchar(200)");
		tableMap.put("MEASUREMENT_CONFIG","bytea");
		tableMap.put("ID","int4");
		tableMap.put("AIQ_PLATFORM_ID","int4");
		tableMap.put("ACTIVE","char(1)");
		tableMap.put("SERVICESAUTOMANAGED","bool");
		hm.put("EAM_AIQ_SERVER",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("NAME","varchar(200)");
		tableMap.put("VERSION","varchar(100)");
		tableMap.put("MTIME","int8");
		tableMap.put("primary","key");
		tableMap.put("MD5","varchar(100)");
		tableMap.put("ID","int4");
		tableMap.put("PATH","varchar(500)");
		tableMap.put("DELETED","bool");
		tableMap.put("DISABLED","bool");
		tableMap.put("CTIME","int8");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_PLUGIN",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("COUNT","int4");
		tableMap.put("ERROR_ID","int4");
		tableMap.put("primary","key");
		tableMap.put("REQSTAT_ID","int4");
		tableMap.put("ID","int4");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_STAT_ERRORS",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("CERT_FILE","bytea");
		tableMap.put("CERT_CHAIN","varchar(10000)");
		tableMap.put("unique","(ALIAS_NAME)");
		tableMap.put("ALIAS_NAME","varchar(128)");
		tableMap.put("primary","key");
		tableMap.put("CERT","varchar(4000)");
		tableMap.put("ID","int4");
		tableMap.put("TYPE","varchar(32)");
		hm.put("EAM_KEYSTORE",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("MAX","float8");
		tableMap.put("COUNT","int4");
		tableMap.put("SVCTYPE","int4");
		tableMap.put("MIN","float8");
		tableMap.put("primary","key");
		tableMap.put("BEGINTIME","int8");
		tableMap.put("ID","int4");
		tableMap.put("SVCREQ_ID","int4");
		tableMap.put("ENDTIME","int8");
		tableMap.put("TOTAL","float8");
		tableMap.put("IPADDR","varchar(20)");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_REQUEST_STAT",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("ENTRY_ID","varchar(95)");
		tableMap.put("STATE","varchar(16)");
		tableMap.put("JOB_GROUP","varchar(200)");
		tableMap.put("IS_STATEFUL","bool");
		tableMap.put("PRIORITY","int4");
		tableMap.put("FIRED_TIME","int8");
		tableMap.put("TRIGGER_NAME","varchar(200)");
		tableMap.put("INSTANCE_NAME","varchar(200)");
		tableMap.put("JOB_NAME","varchar(200)");
		tableMap.put("IS_VOLATILE","bool");
		tableMap.put("primary","key");
		tableMap.put("TRIGGER_GROUP","varchar(200)");
		tableMap.put("REQUESTS_RECOVERY","bool");
		hm.put("QRTZ_FIRED_TRIGGERS",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("VALIDATIONERR","varchar(512)");
		tableMap.put("ID","int4");
		tableMap.put("USERMANAGED","bool");
		tableMap.put("CONTROL_RESPONSE","bytea");
		tableMap.put("PRODUCT_RESPONSE","bytea");
		tableMap.put("AUTOINVENTORY_RESPONSE","bytea");
		tableMap.put("RESPONSE_TIME_RESPONSE","bytea");
		tableMap.put("MEASUREMENT_RESPONSE","bytea");
		tableMap.put("VERSION_COL","int8");
		hm.put("EAM_CONFIG_RESPONSE",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("NAME","varchar(255)");
		tableMap.put("MTIME","int8");
		tableMap.put("DESCRIPTION","varchar(250)");
		tableMap.put("PRIORITY","int4");
		tableMap.put("RESOURCE_ID","int4");
		tableMap.put("CONTROL_FILTERED","bool");
		tableMap.put("NOTIFY_FILTERED","bool");
		tableMap.put("CTIME","int8");
		tableMap.put("VERSION_COL","int8");
		tableMap.put("ENABLED","bool");
		tableMap.put("COUNT","int8");
		tableMap.put("primary","key");
		tableMap.put("ESCALATION_ID","int4");
		tableMap.put("ID","int4");
		tableMap.put("WILL_RECOVER","bool");
		tableMap.put("TRANGE","int8");
		tableMap.put("FREQUENCY_TYPE","int4");
		tableMap.put("DELETED","bool");
		tableMap.put("PARENT_ID","int4");
		tableMap.put("ACTIVE","bool");
		hm.put("EAM_ALERT_DEFINITION",tableMap);
		tableMap = new java.util.HashMap();
		tableMap.put("primary","key");
		tableMap.put("VALUE","numeric(24");
		tableMap.put("MEASUREMENT_ID","int4");
		tableMap.put("TIMESTAMP","int8");
		hm.put("HQ_METRIC_DATA_1D_0S",tableMap);
		return hm ;
	}
}
